### ISSUE TITLE
Change on BED does nothing

### ISSUE THREAD

**Issue by mytdragon** [synopia/bfs2pack#2]
Hello, 

I discovered that software today and I don't know if you are still active after these years. When I changed a texture for a car that works, but when I try to change a `.bed` file, it does nothing.

For example I changed the `fo2a/scripts/classes.bed` and tried to change the first cup of ClassC `Derby Initiation Cup` to `Derby Test Cup` just for test and it changed nothing. Like the texture of the car I've changed, I needed to run a race to see the difference because it keeps the old on the menu, so I tried to change the number of laps but same problem.

Do you have any ideas of why ? My objective is to set the AI harder.

Thanks for reading!

**Comment by TomasHubelbauer** [comment]
I don't think @synopia is watching the issues for this repository, but I will try to reproduce your issue this week to see if I run into the same problem.

**Comment by mytdragon** [comment]
Ok, thank you for the time

**Comment by TomasHubelbauer** [comment]
My apologies, never got to it 😞
